# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_github_packages:
  - yonicd/covrpage

after_sucess:
  - Rscript -e 'covr::codecov()'
  - bash .travis/covrpage.sh
after_failure:
  - bash .travis/covrpage.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
